import { ModelCapabilities } from "../types";

export const anthropicModels: ModelCapabilities[] = [{
    modelName: "claude-opus-4-20250514",
    provider: "anthropic",
    displayName: "Claude Opus 4",
    maxInputTokens: 200000,
    maxOutputTokens: 32000,
    thinking: true,
    minThinkingTokens: 1024,
    maxThinkingTokens: 32000,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-sonnet-4-20250514",
    provider: "anthropic",
    displayName: "Claude Sonnet 4",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    thinking: true,
    minThinkingTokens: 1024,
    maxThinkingTokens: 64000,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-7-sonnet-20250219",
    provider: "anthropic",
    displayName: "Claude Sonnet 3.7",
    maxInputTokens: 200000,
    maxOutputTokens: 64000,
    thinking: true,
    minThinkingTokens: 1024,
    maxThinkingTokens: 128000,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-5-sonnet-20241022",
    provider: "anthropic",
    displayName: "Claude Sonnet 3.5 (New)",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    thinking: false,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-5-haiku-20241022",
    provider: "anthropic",
    displayName: "Claude Haiku 3.5",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    thinking: false,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-5-sonnet-20240620",
    provider: "anthropic",
    displayName: "Claude Sonnet 3.5 (Old)",
    maxInputTokens: 200000,
    maxOutputTokens: 8192,
    thinking: false,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-sonnet-20240229",
    provider: "anthropic",
    displayName: "Claude Sonnet 3",
    maxInputTokens: 200000,
    maxOutputTokens: 4096,
    thinking: false,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-haiku-20240307",
    provider: "anthropic",
    displayName: "Claude Haiku 3",
    maxInputTokens: 200000,
    maxOutputTokens: 4096,
    thinking: false,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}, {
    modelName: "claude-3-opus-20240229",
    provider: "anthropic",
    displayName: "Claude Opus 3",
    maxInputTokens: 200000,
    maxOutputTokens: 4096,
    thinking: false,
    sdk: "anthropic",
    apiKeyName: "ANTHROPIC_API_KEY",
}];

export const openaiModels: ModelCapabilities[] = [{
    modelName: "o4-mini",
    provider: "openai",
    displayName: "OpenAI o4-mini",
    maxInputTokens: 200000,
    maxOutputTokens: 100000,
    thinking: true,
    minThinkingTokens: 1024,
    maxThinkingTokens: 32000,
    sdk: "openai",
    apiKeyName: "OPENAI_API_KEY",
}, {
    modelName: "o3",
    provider: "openai",
    displayName: "OpenAI o3",
    maxInputTokens: 200000,
    maxOutputTokens: 100000,
    thinking: true,
    minThinkingTokens: 1024,
    maxThinkingTokens: 32000,
    sdk: "openai",
    apiKeyName: "OPENAI_API_KEY",
}, {
    modelName: "o3-mini",
    provider: "openai",
    displayName: "OpenAI o3-mini",
    maxInputTokens: 200000,
    maxOutputTokens: 100000,
    thinking: true,
    minThinkingTokens: 1024,
    maxThinkingTokens: 16000,
    sdk: "openai",
    apiKeyName: "OPENAI_API_KEY",
}, {
    modelName: "gpt-4o-mini",
    provider: "openai",
    displayName: "GPT-4o-mini",
    maxInputTokens: 128000,
    maxOutputTokens: 16384,
    thinking: false,
    sdk: "openai",
    apiKeyName: "OPENAI_API_KEY",
}];

export const geminiModels: ModelCapabilities[] = [{
    modelName: "gemini-2.5-pro",
    provider: "gemini",
    displayName: "Gemini 2.5 Pro",
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
    thinking: true,
    minThinkingTokens: 128,
    maxThinkingTokens: 32768,
    sdk: "gemini",
    apiKeyName: "GEMINI_API_KEY",
}, {
    modelName: "gemini-2.5-flash",
    provider: "gemini",
    displayName: "Gemini 2.5 Flash",
    maxInputTokens: 1048576,
    maxOutputTokens: 65535,
    thinking: true,
    minThinkingTokens: 0,
    maxThinkingTokens: 24576,
    sdk: "gemini",
    apiKeyName: "GEMINI_API_KEY",
}, {
    modelName: "gemini-2.5-flash-lite-preview-06-17",
    provider: "gemini",
    displayName: "Gemini 2.5 Flash-Lite",
    maxInputTokens: 1000000,
    maxOutputTokens: 64000,
    thinking: true,
    minThinkingTokens: 512,
    maxThinkingTokens: 24576,
    sdk: "gemini",
    apiKeyName: "GEMINI_API_KEY",
}, {
    modelName: "gemini-2.0-flash",
    provider: "gemini",
    displayName: "Gemini 2.0 Flash",
    maxInputTokens: 1048576,
    maxOutputTokens: 8192,
    thinking: false,
    sdk: "gemini",
    apiKeyName: "GEMINI_API_KEY",
}];

export const otherModels: ModelCapabilities[] = [
    {
    modelName: "kimi-k2-0711-preview",
    provider: "moonshot",
    displayName: "Kimi K2 (Anthropic SDK)",
    maxInputTokens: 128000,
    maxOutputTokens: 8192,
    thinking: false,
    sdk: "anthropic",
    baseUrl: "https://api.moonshot.ai/anthropic/",
    apiKeyName: "MOONSHOT_API_KEY",
},
 {
    modelName: "kimi-k2-0711-preview",
    provider: "moonshot",
    displayName: "Kimi K2 (OpenAI SDK)",
    maxInputTokens: 128000,
    maxOutputTokens: 8192,
    thinking: false,
    sdk: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyName: "MOONSHOT_API_KEY",
}, {
    modelName: "google/gemini-2.5-pro",
    provider: "openrouter",
    displayName: "Gemini 2.5 Pro OR",
    maxInputTokens: 128000,
    maxOutputTokens: 8192,
    thinking: true,
    minThinkingTokens: 128,
    maxThinkingTokens: 32768,
    sdk: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyName: "OPENROUTER_API_KEY",
}];
